name: AutoRelease

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '99.99.99'

permissions:
  contents: write

jobs:
  build_check:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: SetupNuget
        uses: nuget/setup-nuget@v1
      - name: RestoreNugetPackage
        run: nuget restore ExtremeSkins.Generator.sln
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - name: AddMsBuildToPATH
        uses: microsoft/setup-msbuild@v1
      - name: Install 7-Zip
        run: |
          Invoke-WebRequest https://www.7-zip.org/a/7z1900-x64.msi -OutFile 7z.msi
          Start-Process msiexec -ArgumentList '/i','7z.msi','/quiet','/norestart' -Wait
      - name: RunBuild_AllInOne
        run: dotnet publish ExtremeSkins.Generator\ExtremeSkins.Generator.csproj -t:restore,build -p:RestorePackagesConfig=true -p:PublishProfile="Release_AllInOne.pubxml"
      - name: RunBuild_Light
        run: dotnet publish ExtremeSkins.Generator\ExtremeSkins.Generator.csproj -t:restore,build -p:RestorePackagesConfig=true -p:PublishProfile="Release_Light.pubxml"
      - name: Compress_AllInOne
        run: |
          & 'C:\Program Files\7-Zip\7z.exe' a -tzip ExtremeSkins.Generator-AllinOne.zip  D:\a\ExtremeSkins.Generator\ExtremeSkins.Generator\ExtremeSkins.Generator\bin\publish\AllinOne\*
      - name: Compress_Light
        run: |
          & 'C:\Program Files\7-Zip\7z.exe' a -tzip ExtremeSkins.Generator-Light.zip D:\a\ExtremeSkins.Generator\ExtremeSkins.Generator\ExtremeSkins.Generator\bin\publish\Light\*
      - name: CreateRelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          name: "ExtremeSkins.Generator ${{ github.event.inputs.version }}"
          body: "auto release"
          files: |
            ExtremeSkins.Generator-AllinOne.zip
            ExtremeSkins.Generator-Light.zip
